import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Sidebar } from "@/components/sidebar";
import { QueryProvider } from "@/components/querie-provider";
import { ThemeProvider } from "@/components/theme-provider"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
        <div className="max-h-screen">
          <div className="flex w-full h-full">
            <div className="fixed bg-neutral-100 dark:bg-black dark:border-r-2 left-0 top-0 hidden lg:block lg:w-[264px] h-full overflow-y-auto">
              <Sidebar />
            </div>
            <div className="lg:pl-[264px] w-full">
              <div className="mx-auto max-w-screen-2xl h-full">
                <Navbar />
                <main className="h-full py-8 px-6 flex flex-col">
                  <QueryProvider>
                    {children}
                  </QueryProvider>
                </main>
              </div>
            </div>
          </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
